### ISSUE TITLE
todo bien

### ISSUE THREAD

**Issue by magdalenaviloriac** [maestria-geotel-201902/unidad-0-asignacion-2-preguntas-investigacion-magdalenaviloriac#1]
geofis  todo bien

**Comment by geofis** [comment]
Perfecto. Aunque en *issues* no es necesario hacer mención para que me llegue mensaje al correo, puedes mencionar usuarios si quieres dirigirte a ellos de manera expresa. En *commit* es diferente, allí sí que necesitas hacer mención para que me llegue mensaje de correo. Recuerda, el nombre de usuario del mencionado debe precederse por arroba (@) para que surta efecto.
